import type { Country, DataCategory, Dataset } from "@shared/schema";

//todo: remove mock functionality - China datasets
const chinaDemandDatasets: Dataset[] = [
  {
    id: "china-demand-provincial-yearly",
    country: "China",
    category: "Demand",
    name: "Provincial Yearly Demand",
    description: "This dataset contains China's provincial yearly power consumption data. The data is collected from the National Bureau of Statistics of China (NBS). The data is updated annually, typically in June each year.",
    format: "CSV",
    size: "16 KB",
    updated: "2024-06-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data aggregated from provincial grid operators and compiled annually. Quality control includes validation against national totals.",
    about: `The National Bureau of Statistics (NBS) is the source of national and some provincial official statistical data in China. The NBS notes that provincial yearly power consumption data is sourced from the China Electricity Council (CEC).`,
    citation: "Open Power Data Initiative. \"Provincial Yearly Demand - China\". Open Power Data, 2024. DOI: 10.5281/opd.china.demand.yearly",
    startDate: "2010",
    endDate: "2023",
    Link: "https://data.stats.gov.cn/easyquery.htm?cn=E0103",
    UserAgreement: "https://data.stats.gov.cn/login.htm?m=toDisclimer",
    preview: [
      { year: 2023, province: "Guangdong", demand_TWh: 782.5, population_million: 126.8 },
      { year: 2023, province: "Jiangsu", demand_TWh: 721.3, population_million: 85.1 },
      { year: 2023, province: "Shandong", demand_TWh: 689.4, population_million: 101.6 },
    ],
  },
  {
    id: "china-demand-provincial-monthly",
    country: "China",
    category: "Demand",
    name: "Provincial Monthly Demand",
    description: "Monthly electricity demand data by province",
    format: "CSV, JSON",
    size: "18.6 MB",
    updated: "2024-10-01",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Monthly data compiled from provincial electricity authorities with seasonal adjustments applied.",
    about: "Monthly electricity demand patterns across Chinese provinces showing seasonal variations.",
    preview: [
      { year_month: "2024-01", province: "Guangdong", demand_TWh: 68.2, avg_temp_C: 14.5 },
      { year_month: "2024-02", province: "Guangdong", demand_TWh: 59.7, avg_temp_C: 16.2 },
      { year_month: "2024-03", province: "Guangdong", demand_TWh: 65.4, avg_temp_C: 20.1 },
    ],
  },
  {
    id: "china-demand-provincial-hourly",
    country: "China",
    category: "Demand",
    name: "Provincial Hourly Demand",
    description: "Hourly electricity demand data by province",
    format: "CSV",
    size: "10.7 MB",
    updated: "2024-10-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Real-time data from grid operators aggregated to hourly intervals with automated quality checks.",
    about: "High-resolution hourly electricity demand data enabling detailed load profile analysis.",
    preview: [
      { province: "Anhui", year: 2022, month: 1, day: 1, hour: 1, load_mw: 32973.3918 },
      { province: "Anhui", year: 2022, month: 1, day: 1, hour: 2, load_mw: 31288.18473 },
      { province: "Anhui", year: 2022, month: 1, day: 1, hour: 3, load_mw: 30282.50421 },   
    ],
  },
];

const chinaSupplyDatasets: Dataset[] = [
  {
    id: "china-generator-coal",
    country: "China",
    category: "Supply",
    name: "Generator: Coal",
    description: "Coal-fired power plant registry and specifications",
    format: "CSV, JSON",
    size: "4.2 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Compiled from National Energy Administration records and provincial regulatory filings.",
    about: "Comprehensive database of coal-fired generating units including capacity, technology type, and operational status.",
    preview: [
      { plant_name: "Tuoketuo Power Station", province: "Inner Mongolia", capacity_MW: 6720, units: 8, commissioned_year: 2006 },
      { plant_name: "Waigaoqiao Power Station", province: "Shanghai", capacity_MW: 5000, units: 4, commissioned_year: 2008 },
    ],
  },
  {
    id: "china-generator-gas",
    country: "China",
    category: "Supply",
    name: "Generator: Gas",
    description: "Natural gas power plant registry",
    format: "CSV, JSON",
    size: "1.8 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from provincial energy authorities with verification against grid connection records.",
    about: "Registry of natural gas-fired power plants with technical specifications.",
    preview: [
      { plant_name: "Zhuhai LNG Power Plant", province: "Guangdong", capacity_MW: 1980, units: 3, fuel_type: "LNG" },
    ],
  },
  {
    id: "china-generator-hydro",
    country: "China",
    category: "Supply",
    name: "Generator: Hydro",
    description: "Hydroelectric power plant database",
    format: "CSV, JSON",
    size: "3.5 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Compiled from China Electricity Council and provincial water resources departments.",
    about: "Hydroelectric facility registry including pumped storage and conventional hydro plants.",
    preview: [
      { plant_name: "Three Gorges Dam", province: "Hubei", capacity_MW: 22500, type: "Conventional", reservoir_capacity_million_m3: 39300 },
    ],
  },
  {
    id: "china-generator-nuclear",
    country: "China",
    category: "Supply",
    name: "Generator: Nuclear",
    description: "Nuclear power plant registry",
    format: "CSV, JSON",
    size: "0.6 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Official data from China National Nuclear Corporation and regulatory authorities.",
    about: "Complete registry of operational nuclear power reactors with technical specifications.",
    preview: [
      { plant_name: "Taishan Nuclear Power Plant", province: "Guangdong", capacity_MW: 3510, units: 2, reactor_type: "EPR" },
    ],
  },
  {
    id: "china-generator-wind",
    country: "China",
    category: "Supply",
    name: "Generator: Wind",
    description: "Wind farm registry and specifications",
    format: "CSV, JSON",
    size: "12.4 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from National Energy Administration renewable energy database.",
    about: "Comprehensive wind farm database including onshore and offshore installations.",
    preview: [
      { farm_name: "Gansu Wind Farm", province: "Gansu", capacity_MW: 7965, turbines: 3500, type: "Onshore" },
    ],
  },
  {
    id: "china-generator-solar",
    country: "China",
    category: "Supply",
    name: "Generator: Solar",
    description: "Solar power plant registry",
    format: "CSV, JSON",
    size: "15.7 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Compiled from provincial energy bureaus and grid connection records.",
    about: "Solar photovoltaic and concentrated solar power plant database.",
    preview: [
      { plant_name: "Longyangxia Dam Solar Park", province: "Qinghai", capacity_MW: 850, type: "PV", land_area_km2: 9.16 },
    ],
  },
  {
    id: "china-generator-storage",
    country: "China",
    category: "Supply",
    name: "Generator: Storage",
    description: "Energy storage facility registry",
    format: "CSV, JSON",
    size: "2.1 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from National Energy Administration energy storage statistics.",
    about: "Battery and pumped hydro storage facilities including capacity and operational parameters.",
    preview: [
      { facility_name: "Guangzhou Pumped Storage", province: "Guangdong", capacity_MW: 2400, storage_MWh: 19200, type: "Pumped Hydro" },
    ],
  },
  {
    id: "china-generation-provincial-yearly",
    country: "China",
    category: "Supply",
    name: "Generation: Provincial, by Tech, Yearly",
    description: "Annual generation by province and technology",
    format: "CSV, JSON",
    size: "3.8 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Annual statistics from provincial grid operators aggregated by technology type.",
    about: "Yearly electricity generation data broken down by province and generation technology.",
    preview: [
      { year: 2023, province: "Guangdong", technology: "Coal", generation_TWh: 245.7 },
      { year: 2023, province: "Guangdong", technology: "Gas", generation_TWh: 68.3 },
      { year: 2023, province: "Guangdong", technology: "Nuclear", generation_TWh: 152.4 },
    ],
  },
  {
    id: "china-generation-provincial-monthly-nbs",
    country: "China",
    category: "Supply",
    name: "Generation: Provincial, by Tech, Monthly (NBS)",
    description: "Monthly generation statistics from National Bureau of Statistics",
    format: "CSV, JSON",
    size: "28.5 MB",
    updated: "2024-10-01",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Official monthly statistics from National Bureau of Statistics.",
    about: "Monthly electricity generation by province and technology from official government sources.",
    preview: [
      { year_month: "2024-01", province: "Guangdong", technology: "Coal", generation_TWh: 21.2 },
      { year_month: "2024-01", province: "Guangdong", technology: "Nuclear", generation_TWh: 12.8 },
    ],
  },
  {
    id: "china-capacity-provincial-yearly",
    country: "China",
    category: "Supply",
    name: "Capacity: Provincial, by Tech, Yearly",
    description: "Annual installed capacity by province and technology",
    format: "CSV, JSON",
    size: "2.9 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Year-end capacity statistics from provincial energy authorities.",
    about: "Installed generation capacity by province and technology type at year end.",
    preview: [
      { year: 2023, province: "Guangdong", technology: "Coal", capacity_MW: 56780 },
      { year: 2023, province: "Guangdong", technology: "Gas", capacity_MW: 18950 },
    ],
  },
  {
    id: "china-capacity-provincial-monthly",
    country: "China",
    category: "Supply",
    name: "Capacity: Provincial, by Tech, Monthly",
    description: "Monthly installed capacity tracking",
    format: "CSV, JSON",
    size: "22.4 MB",
    updated: "2024-10-01",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Monthly capacity additions from grid connection approvals.",
    about: "Monthly tracking of installed capacity changes by province and technology.",
    preview: [
      { year_month: "2024-01", province: "Guangdong", technology: "Solar", capacity_MW: 12450, new_additions_MW: 320 },
    ],
  },
  {
    id: "china-capacity-pv-breakdown-yearly",
    country: "China",
    category: "Supply",
    name: "Capacity: Provincial, PV Breakdown, Yearly (Featured)",
    description: "Detailed solar PV capacity breakdown by installation type",
    format: "CSV, JSON",
    size: "4.1 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Comprehensive survey of PV installations categorized by scale and application.",
    about: "Featured dataset providing detailed breakdown of solar PV capacity by utility-scale, distributed, and rooftop installations.",
    preview: [
      { year: 2023, province: "Shandong", utility_scale_MW: 18650, distributed_MW: 12340, rooftop_MW: 8920 },
    ],
  },
];

const chinaTransmissionDatasets: Dataset[] = [
  {
    id: "china-network-above-500kv",
    country: "China",
    category: "Transmission",
    name: "Network: Above 500kV",
    description: "High voltage transmission network including DC and AC systems",
    format: "CSV, GeoJSON",
    size: "8.3 MB",
    updated: "2024-09-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Network topology from State Grid Corporation and China Southern Power Grid.",
    about: "Transmission lines rated 500kV and above including UHVDC (±800kV, ±1100kV) and UHVAC (1000kV, 750kV).",
    preview: [
      { line_name: "Xiangjiaba-Shanghai ±800kV UHVDC", voltage_kV: 800, type: "DC", capacity_MW: 6400, length_km: 1907 },
    ],
  },
  {
    id: "china-network-500kv-guangdong",
    country: "China",
    category: "Transmission",
    name: "Network: 500kV (Within Guangdong)",
    description: "500kV transmission network within Guangdong Province",
    format: "CSV, GeoJSON",
    size: "1.2 MB",
    updated: "2024-09-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Detailed network data from Guangdong Power Grid Company.",
    about: "Complete 500kV transmission infrastructure within Guangdong Province.",
    preview: [
      { line_name: "Guangzhou-Shenzhen 500kV Line 1", substations: "Guangzhou North - Shenzhen West", length_km: 145 },
    ],
  },
  {
    id: "china-transmission-interprovincial-yearly",
    country: "China",
    category: "Transmission",
    name: "Transmission: Yearly Flow, Interprovincial",
    description: "Annual electricity transfer between provinces",
    format: "CSV, JSON",
    size: "2.7 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Annual settlement data from regional grid operators.",
    about: "Yearly electricity flow data for interprovincial transmission corridors.",
    preview: [
      { year: 2023, from_province: "Yunnan", to_province: "Guangdong", flow_TWh: 87.3, revenue_million_CNY: 32450 },
    ],
  },
  {
    id: "china-transmission-interregional-yearly",
    country: "China",
    category: "Transmission",
    name: "Transmission: Yearly Flow, Interregional",
    description: "Annual electricity transfer between regional grids",
    format: "CSV, JSON",
    size: "1.4 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from regional grid coordination centers.",
    about: "Electricity flow between China's major regional grids (North, Northeast, East, Central, Northwest, South).",
    preview: [
      { year: 2023, from_region: "Northwest", to_region: "Central", flow_TWh: 45.2 },
    ],
  },
  {
    id: "china-transmission-east-hourly",
    country: "China",
    category: "Transmission",
    name: "Transmission: Hourly Flow, East China",
    description: "Hourly transmission flows within East China Grid",
    format: "CSV, JSON",
    size: "145.8 MB",
    updated: "2024-10-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Real-time SCADA data from East China Grid dispatch center.",
    about: "High-resolution hourly transmission flow data for major corridors in East China.",
    preview: [
      { timestamp: "2024-01-01 00:00", corridor: "Anhui-Jiangsu", flow_MW: 2340, direction: "export" },
    ],
  },
  {
    id: "china-transmission-north-hourly",
    country: "China",
    category: "Transmission",
    name: "Transmission: Hourly Flow, North China",
    description: "Hourly transmission flows within North China Grid",
    format: "CSV, JSON",
    size: "132.4 MB",
    updated: "2024-10-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Real-time SCADA data from North China Grid dispatch center.",
    about: "High-resolution hourly transmission flow data for major corridors in North China.",
    preview: [
      { timestamp: "2024-01-01 00:00", corridor: "Inner Mongolia-Beijing", flow_MW: 3560, direction: "export" },
    ],
  },
  {
    id: "china-transmission-south-hourly",
    country: "China",
    category: "Transmission",
    name: "Transmission: Hourly Flow, South China",
    description: "Hourly transmission flows within South China Grid",
    format: "CSV, JSON",
    size: "98.6 MB",
    updated: "2024-10-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Real-time SCADA data from China Southern Power Grid dispatch center.",
    about: "High-resolution hourly transmission flow data for major corridors in South China.",
    preview: [
      { timestamp: "2024-01-01 00:00", corridor: "Yunnan-Guangdong", flow_MW: 4120, direction: "export" },
    ],
  },
];

const chinaREResourceDatasets: Dataset[] = [
  {
    id: "china-wind-monthly-profile",
    country: "China",
    category: "RE Resource Potential",
    name: "Wind: Provincial Monthly Wind Profile",
    description: "Monthly wind speed and capacity factor profiles by province",
    format: "CSV, JSON",
    size: "6.2 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Meteorological data from China Meteorological Administration processed for wind energy assessment.",
    about: "Monthly wind resource profiles enabling seasonal generation pattern analysis.",
    preview: [
      { year_month: "2024-01", province: "Inner Mongolia", avg_wind_speed_ms: 7.8, capacity_factor: 0.42 },
    ],
  },
  {
    id: "china-wind-hourly-profile",
    country: "China",
    category: "RE Resource Potential",
    name: "Wind: Provincial Hourly Wind Profile",
    description: "Hourly wind speed and capacity factor profiles by province",
    format: "CSV, JSON",
    size: "284.5 MB",
    updated: "2024-10-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "High-resolution meteorological data processed with wind turbine power curves.",
    about: "Hourly wind resource data for detailed renewable energy integration studies.",
    preview: [
      { timestamp: "2024-01-01 00:00", province: "Inner Mongolia", wind_speed_ms: 8.2, capacity_factor: 0.45, power_density_Wm2: 520 },
    ],
  },
  {
    id: "china-solar-monthly-profile",
    country: "China",
    category: "RE Resource Potential",
    name: "Solar: Provincial Monthly Solar Profile",
    description: "Monthly solar irradiance and capacity factor profiles by province",
    format: "CSV, JSON",
    size: "4.8 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Satellite-derived solar irradiance data calibrated with ground measurements.",
    about: "Monthly solar resource profiles for PV generation assessment.",
    preview: [
      { year_month: "2024-01", province: "Qinghai", ghi_kWh_m2: 142.5, capacity_factor: 0.18 },
    ],
  },
  {
    id: "china-solar-hourly-profile",
    country: "China",
    category: "RE Resource Potential",
    name: "Solar: Provincial Hourly Solar Profile",
    description: "Hourly solar irradiance and capacity factor profiles by province",
    format: "CSV, JSON",
    size: "198.3 MB",
    updated: "2024-10-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Satellite-derived hourly irradiance with atmospheric corrections.",
    about: "Hourly solar resource data for high-resolution PV generation modeling.",
    preview: [
      { timestamp: "2024-01-01 12:00", province: "Qinghai", ghi_W_m2: 785, dni_W_m2: 892, capacity_factor: 0.65 },
    ],
  },
];

const chinaParametersDatasets: Dataset[] = [
  {
    id: "china-coal-price-index",
    country: "China",
    category: "Parameters",
    name: "Fuel: Coal Price Index",
    description: "Coal price indices by region and quality",
    format: "CSV, JSON",
    size: "1.2 MB",
    updated: "2024-10-25",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Price data from Bohai-Rim Steam-Coal Price Index and provincial coal exchanges.",
    about: "Monthly coal price indices for different qualities and delivery locations.",
    preview: [
      { year_month: "2024-09", region: "Qinhuangdao", quality: "5500 kcal/kg", price_CNY_ton: 950 },
    ],
  },
  {
    id: "china-gas-price-index",
    country: "China",
    category: "Parameters",
    name: "Fuel: Gas Price Index",
    description: "Natural gas price indices by region",
    format: "CSV, JSON",
    size: "0.8 MB",
    updated: "2024-10-25",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Price data from Shanghai Petroleum and Natural Gas Exchange and regional markets.",
    about: "Monthly natural gas price indices including LNG and pipeline gas.",
    preview: [
      { year_month: "2024-09", region: "Shanghai", type: "Pipeline", price_CNY_m3: 2.85 },
    ],
  },
];

// India datasets
const indiaDemandDatasets: Dataset[] = [
  {
    id: "india-demand-state-yearly",
    country: "India",
    category: "Demand",
    name: "State Yearly Demand",
    description: "Annual electricity demand data by state",
    format: "CSV, JSON",
    size: "1.8 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data compiled from state load dispatch centers and Central Electricity Authority reports.",
    about: "Annual electricity consumption by Indian states.",
    preview: [
      { year: 2023, state: "Maharashtra", demand_TWh: 156.2, population_million: 124.9 },
      { year: 2023, state: "Gujarat", demand_TWh: 112.8, population_million: 70.1 },
    ],
  },
];

const indiaSupplyDatasets: Dataset[] = [
  {
    id: "india-generator-coal",
    country: "India",
    category: "Supply",
    name: "Generator: Coal",
    description: "Coal-fired power plant registry",
    format: "CSV, JSON",
    size: "3.2 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from Central Electricity Authority power plant database.",
    about: "Registry of coal-fired power plants with capacity and operational details.",
    preview: [
      { plant_name: "Vindhyachal Super Thermal", state: "Madhya Pradesh", capacity_MW: 4760, units: 12 },
    ],
  },
  {
    id: "india-generation-state-yearly",
    country: "India",
    category: "Supply",
    name: "Generation: State, by Tech, Yearly",
    description: "Annual generation by state and technology",
    format: "CSV, JSON",
    size: "2.1 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Annual statistics from Central Electricity Authority.",
    about: "Yearly electricity generation by state and technology type.",
    preview: [
      { year: 2023, state: "Maharashtra", technology: "Coal", generation_TWh: 89.4 },
    ],
  },
];

const indiaTransmissionDatasets: Dataset[] = [
  {
    id: "india-network-765kv",
    country: "India",
    category: "Transmission",
    name: "Network: 765kV",
    description: "Ultra high voltage transmission network",
    format: "CSV, GeoJSON",
    size: "2.4 MB",
    updated: "2024-08-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Network data from Power Grid Corporation of India.",
    about: "765kV transmission lines and substations across India.",
    preview: [
      { line_name: "Bhadrawati-Dharamjaygarh", voltage_kV: 765, length_km: 385 },
    ],
  },
];

const indiaREResourceDatasets: Dataset[] = [
  {
    id: "india-solar-state-monthly",
    country: "India",
    category: "RE Resource Potential",
    name: "Solar: State Monthly Profile",
    description: "Monthly solar irradiance by state",
    format: "CSV, JSON",
    size: "3.2 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Satellite data from NREL and IMD ground measurements.",
    about: "Monthly solar resource assessment for Indian states.",
    preview: [
      { year_month: "2024-01", state: "Rajasthan", ghi_kWh_m2: 156.8, capacity_factor: 0.22 },
    ],
  },
];

const indiaParametersDatasets: Dataset[] = [
  {
    id: "india-coal-price",
    country: "India",
    category: "Parameters",
    name: "Fuel: Coal Price",
    description: "Coal price by grade and region",
    format: "CSV, JSON",
    size: "0.6 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Price data from Coal India Limited and regional coal exchanges.",
    about: "Monthly coal prices by grade and delivery location.",
    preview: [
      { year_month: "2024-09", grade: "G11", region: "South Eastern", price_INR_ton: 2850 },
    ],
  },
];

// Indonesia datasets
const indonesiaDemandDatasets: Dataset[] = [
  {
    id: "indonesia-demand-regional-yearly",
    country: "Indonesia",
    category: "Demand",
    name: "Regional Yearly Demand",
    description: "Annual electricity demand by region",
    format: "CSV, JSON",
    size: "0.8 MB",
    updated: "2024-09-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from PLN (Perusahaan Listrik Negara) regional offices.",
    about: "Annual electricity consumption by Indonesian regions.",
    preview: [
      { year: 2023, region: "Java-Bali", demand_TWh: 198.5, population_million: 151.6 },
    ],
  },
];

const indonesiaSupplyDatasets: Dataset[] = [
  {
    id: "indonesia-generator-coal",
    country: "Indonesia",
    category: "Supply",
    name: "Generator: Coal",
    description: "Coal-fired power plant registry",
    format: "CSV, JSON",
    size: "1.4 MB",
    updated: "2024-09-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from Ministry of Energy and Mineral Resources.",
    about: "Registry of coal power plants in Indonesia.",
    preview: [
      { plant_name: "Suralaya", region: "Java-Bali", capacity_MW: 4025, units: 7 },
    ],
  },
];

const indonesiaTransmissionDatasets: Dataset[] = [
  {
    id: "indonesia-network-500kv",
    country: "Indonesia",
    category: "Transmission",
    name: "Network: 500kV Java-Bali",
    description: "500kV transmission network in Java-Bali system",
    format: "CSV, GeoJSON",
    size: "1.1 MB",
    updated: "2024-08-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Network data from PLN transmission division.",
    about: "High voltage transmission infrastructure in Java-Bali grid.",
    preview: [
      { line_name: "Surabaya Barat-Gresik", voltage_kV: 500, length_km: 42 },
    ],
  },
];

const indonesiaREResourceDatasets: Dataset[] = [
  {
    id: "indonesia-solar-regional-monthly",
    country: "Indonesia",
    category: "RE Resource Potential",
    name: "Solar: Regional Monthly Profile",
    description: "Monthly solar irradiance by region",
    format: "CSV, JSON",
    size: "1.6 MB",
    updated: "2024-09-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Satellite-derived irradiance data calibrated with ground stations.",
    about: "Monthly solar resource assessment for Indonesian regions.",
    preview: [
      { year_month: "2024-01", region: "Java-Bali", ghi_kWh_m2: 145.2, capacity_factor: 0.19 },
    ],
  },
];

const indonesiaParametersDatasets: Dataset[] = [
  {
    id: "indonesia-coal-price",
    country: "Indonesia",
    category: "Parameters",
    name: "Fuel: Coal Reference Price (HBA)",
    description: "Indonesian Coal Reference Price",
    format: "CSV, JSON",
    size: "0.3 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Official HBA (Harga Batubara Acuan) from Ministry of Energy.",
    about: "Monthly Indonesian coal benchmark price.",
    preview: [
      { year_month: "2024-09", hba_USD_ton: 98.5 },
    ],
  },
];

// Vietnam datasets
const vietnamDemandDatasets: Dataset[] = [
  {
    id: "vietnam-demand-regional-yearly",
    country: "Vietnam",
    category: "Demand",
    name: "Regional Yearly Demand",
    description: "Annual electricity demand by region",
    format: "CSV, JSON",
    size: "0.6 MB",
    updated: "2024-09-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from Vietnam Electricity (EVN) regional companies.",
    about: "Annual electricity consumption by Vietnamese regions.",
    preview: [
      { year: 2023, region: "Southern", demand_TWh: 89.4, population_million: 36.2 },
    ],
  },
];

const vietnamSupplyDatasets: Dataset[] = [
  {
    id: "vietnam-generator-coal",
    country: "Vietnam",
    category: "Supply",
    name: "Generator: Coal",
    description: "Coal-fired power plant registry",
    format: "CSV, JSON",
    size: "1.1 MB",
    updated: "2024-09-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from Ministry of Industry and Trade power development plan.",
    about: "Registry of coal power plants in Vietnam.",
    preview: [
      { plant_name: "Vinh Tan", region: "Southern", capacity_MW: 4400, units: 4 },
    ],
  },
];

const vietnamTransmissionDatasets: Dataset[] = [
  {
    id: "vietnam-network-500kv",
    country: "Vietnam",
    category: "Transmission",
    name: "Network: 500kV",
    description: "500kV transmission network",
    format: "CSV, GeoJSON",
    size: "0.9 MB",
    updated: "2024-08-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Network data from National Load Dispatch Center.",
    about: "500kV transmission backbone across Vietnam.",
    preview: [
      { line_name: "Pleiku-Mang Yang", voltage_kV: 500, length_km: 78 },
    ],
  },
];

const vietnamREResourceDatasets: Dataset[] = [
  {
    id: "vietnam-wind-regional-monthly",
    country: "Vietnam",
    category: "RE Resource Potential",
    name: "Wind: Regional Monthly Profile",
    description: "Monthly wind resource by region",
    format: "CSV, JSON",
    size: "1.2 MB",
    updated: "2024-09-20",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Wind resource assessment from meteorological data and wind atlas.",
    about: "Monthly wind resource potential for Vietnamese regions.",
    preview: [
      { year_month: "2024-01", region: "Southern", avg_wind_speed_ms: 6.8, capacity_factor: 0.32 },
    ],
  },
];

const vietnamParametersDatasets: Dataset[] = [
  {
    id: "vietnam-coal-import-price",
    country: "Vietnam",
    category: "Parameters",
    name: "Fuel: Coal Import Price",
    description: "Imported coal price index",
    format: "CSV, JSON",
    size: "0.4 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Import price data from General Department of Customs.",
    about: "Monthly imported coal prices for power generation.",
    preview: [
      { year_month: "2024-09", origin: "Indonesia", price_USD_ton: 105.2 },
    ],
  },
];

// ASEAN datasets
const aseanDemandDatasets: Dataset[] = [
  {
    id: "asean-demand-country-yearly",
    country: "ASEAN",
    category: "Demand",
    name: "Country Yearly Demand",
    description: "Annual electricity demand by ASEAN country",
    format: "CSV, JSON",
    size: "0.5 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data compiled from ASEAN Centre for Energy statistics.",
    about: "Annual electricity consumption for ASEAN member states.",
    preview: [
      { year: 2023, country: "Thailand", demand_TWh: 198.7, population_million: 71.8 },
      { year: 2023, country: "Malaysia", demand_TWh: 165.3, population_million: 33.9 },
    ],
  },
];

const aseanSupplyDatasets: Dataset[] = [
  {
    id: "asean-capacity-country-yearly",
    country: "ASEAN",
    category: "Supply",
    name: "Capacity: Country, by Tech, Yearly",
    description: "Annual installed capacity by country and technology",
    format: "CSV, JSON",
    size: "1.4 MB",
    updated: "2024-09-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Compiled from national energy statistics and ASEAN Energy Database.",
    about: "Installed generation capacity across ASEAN countries by technology.",
    preview: [
      { year: 2023, country: "Thailand", technology: "Gas", capacity_MW: 28450 },
    ],
  },
];

const aseanTransmissionDatasets: Dataset[] = [
  {
    id: "asean-interconnection",
    country: "ASEAN",
    category: "Transmission",
    name: "ASEAN Power Grid Interconnections",
    description: "Cross-border transmission interconnections",
    format: "CSV, GeoJSON",
    size: "0.7 MB",
    updated: "2024-08-30",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Data from ASEAN Power Grid study and bilateral agreements.",
    about: "Cross-border electricity transmission infrastructure.",
    preview: [
      { interconnection: "Thailand-Laos", voltage_kV: 230, capacity_MW: 2450 },
    ],
  },
];

const aseanREResourceDatasets: Dataset[] = [
  {
    id: "asean-solar-country-potential",
    country: "ASEAN",
    category: "RE Resource Potential",
    name: "Solar: Country Potential Assessment",
    description: "Solar energy potential by ASEAN country",
    format: "CSV, JSON",
    size: "1.8 MB",
    updated: "2024-09-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Regional solar resource assessment from satellite data.",
    about: "Technical solar energy potential across ASEAN countries.",
    preview: [
      { country: "Thailand", avg_ghi_kWh_m2_year: 1825, technical_potential_GW: 143 },
    ],
  },
];

const aseanParametersDatasets: Dataset[] = [
  {
    id: "asean-lng-price",
    country: "ASEAN",
    category: "Parameters",
    name: "Fuel: LNG Import Price",
    description: "Regional LNG import price index",
    format: "CSV, JSON",
    size: "0.5 MB",
    updated: "2024-10-15",
    license: "CC BY 4.0",
    downloadUrl: "#",
    methodology: "Import price data from national customs and energy ministries.",
    about: "Monthly LNG import prices for ASEAN countries.",
    preview: [
      { year_month: "2024-09", country: "Thailand", price_USD_mmbtu: 13.2 },
    ],
  },
];

//todo: remove mock functionality
export const Countries: Country[] = [
  {
    id: "china",
    name: "China",
    flag: "🇨🇳",
    datasetCount: 29,
    categories: [
      {
        id: "demand",
        name: "Demand",
        icon: "TrendingUp",
        datasets: chinaDemandDatasets,
      },
      {
        id: "supply",
        name: "Supply",
        icon: "Zap",
        datasets: chinaSupplyDatasets,
      },
      {
        id: "transmission",
        name: "Transmission",
        icon: "Network",
        datasets: chinaTransmissionDatasets,
      },
      {
        id: "re-resource",
        name: "RE Resource Potential",
        icon: "Sun",
        datasets: chinaREResourceDatasets,
      },
      {
        id: "parameters",
        name: "Parameters",
        icon: "DollarSign",
        datasets: chinaParametersDatasets,
      },
    ],
  },
  {
    id: "india",
    name: "India",
    flag: "🇮🇳",
    datasetCount: 5,
    categories: [
      {
        id: "demand",
        name: "Demand",
        icon: "TrendingUp",
        datasets: indiaDemandDatasets,
      },
      {
        id: "supply",
        name: "Supply",
        icon: "Zap",
        datasets: indiaSupplyDatasets,
      },
      {
        id: "transmission",
        name: "Transmission",
        icon: "Network",
        datasets: indiaTransmissionDatasets,
      },
      {
        id: "re-resource",
        name: "RE Resource Potential",
        icon: "Sun",
        datasets: indiaREResourceDatasets,
      },
      {
        id: "parameters",
        name: "Parameters",
        icon: "DollarSign",
        datasets: indiaParametersDatasets,
      },
    ],
  },
  {
    id: "indonesia",
    name: "Indonesia",
    flag: "🇮🇩",
    datasetCount: 5,
    categories: [
      {
        id: "demand",
        name: "Demand",
        icon: "TrendingUp",
        datasets: indonesiaDemandDatasets,
      },
      {
        id: "supply",
        name: "Supply",
        icon: "Zap",
        datasets: indonesiaSupplyDatasets,
      },
      {
        id: "transmission",
        name: "Transmission",
        icon: "Network",
        datasets: indonesiaTransmissionDatasets,
      },
      {
        id: "re-resource",
        name: "RE Resource Potential",
        icon: "Sun",
        datasets: indonesiaREResourceDatasets,
      },
      {
        id: "parameters",
        name: "Parameters",
        icon: "DollarSign",
        datasets: indonesiaParametersDatasets,
      },
    ],
  },
  {
    id: "vietnam",
    name: "Vietnam",
    flag: "🇻🇳",
    datasetCount: 5,
    categories: [
      {
        id: "demand",
        name: "Demand",
        icon: "TrendingUp",
        datasets: vietnamDemandDatasets,
      },
      {
        id: "supply",
        name: "Supply",
        icon: "Zap",
        datasets: vietnamSupplyDatasets,
      },
      {
        id: "transmission",
        name: "Transmission",
        icon: "Network",
        datasets: vietnamTransmissionDatasets,
      },
      {
        id: "re-resource",
        name: "RE Resource Potential",
        icon: "Sun",
        datasets: vietnamREResourceDatasets,
      },
      {
        id: "parameters",
        name: "Parameters",
        icon: "DollarSign",
        datasets: vietnamParametersDatasets,
      },
    ],
  },
  {
    id: "asean",
    name: "Subset of ASEAN Countries",
    flag: "🌏",
    datasetCount: 5,
    categories: [
      {
        id: "demand",
        name: "Demand",
        icon: "TrendingUp",
        datasets: aseanDemandDatasets,
      },
      {
        id: "supply",
        name: "Supply",
        icon: "Zap",
        datasets: aseanSupplyDatasets,
      },
      {
        id: "transmission",
        name: "Transmission",
        icon: "Network",
        datasets: aseanTransmissionDatasets,
      },
      {
        id: "re-resource",
        name: "RE Resource Potential",
        icon: "Sun",
        datasets: aseanREResourceDatasets,
      },
      {
        id: "parameters",
        name: "Parameters",
        icon: "DollarSign",
        datasets: aseanParametersDatasets,
      },
    ],
  },
];

//todo: remove mock functionality
export const powerDatasets: Dataset[] = [
  ...chinaDemandDatasets,
  ...chinaSupplyDatasets,
  ...chinaTransmissionDatasets,
  ...chinaREResourceDatasets,
  ...chinaParametersDatasets,
  ...indiaDemandDatasets,
  ...indiaSupplyDatasets,
  ...indiaTransmissionDatasets,
  ...indiaREResourceDatasets,
  ...indiaParametersDatasets,
  ...indonesiaDemandDatasets,
  ...indonesiaSupplyDatasets,
  ...indonesiaTransmissionDatasets,
  ...indonesiaREResourceDatasets,
  ...indonesiaParametersDatasets,
  ...vietnamDemandDatasets,
  ...vietnamSupplyDatasets,
  ...vietnamTransmissionDatasets,
  ...vietnamREResourceDatasets,
  ...vietnamParametersDatasets,
  ...aseanDemandDatasets,
  ...aseanSupplyDatasets,
  ...aseanTransmissionDatasets,
  ...aseanREResourceDatasets,
  ...aseanParametersDatasets,
];
